version: '3'

volumes:
  postgres-data:

services:
  database:
    image: postgres

    ports:
      - ${BOT_DATABASE_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${BOT_DATABASE_USER}
      POSTGRES_PASSWORD: ${BOT_DATABASE_PASSWORD}
      POSTGRES_DB: ${BOT_DATABASE_DATABASE}

  bot:
    image: birthday_bot
    env_file: ./.env
    depends_on:
      - database
