version: '3'

services:
  database:
    image: postgres

    ports:
      - ${BOT_DATABASE_PORT}:5432

    environment:
      POSTGRES_USER: ${BOT_DATABASE_USER}
      POSTGRES_PASSWORD: ${BOT_DATABASE_PASSWORD}
      POSTGRES_DB: ${BOT_DATABASE_DATABASE}

  bot:
    image: birthday_bot
    env_file: ./.env
    depends_on:
      - database
