version: '3'

services:
  database:
    image: postgres

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: discord_bot
      POSTGRES_PASSWORD: yog@vD9hmq4CGgDzNHP
      POSTGRES_DB: discord_bot

  bot:
    image: birthday_bot
    depends_on:
      - database
